
version: '3.6'
services:
  jenkins-jnlp-slave:
    build:
      context: .
      dockerfile: Dockerfile
    image: home1oss/jenkins-jnlp-slave:3.20-bionic
    restart: always

    container_name: ${JENKINS_SLAVE_DOMAIN:-jenkins-jnlp-slave}.${INFRASTRUCTURE:-local}
    hostname: ${JENKINS_SLAVE_DOMAIN:-jenkins-jnlp-slave}.${INFRASTRUCTURE:-local}
    #external_links:
    #- jenkins.${INFRASTRUCTURE:-local}:jenkins.${INFRASTRUCTURE:-local}
    #- nexus.${INFRASTRUCTURE:-local}:nexus3.${INFRASTRUCTURE:-local}
    #- mvnsite.${INFRASTRUCTURE:-local}:mvnsite.${INFRASTRUCTURE:-local}
    volumes:
    - volume-jenkins-jnlp-slave:/home/jenkins/.jenkins
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - CI_INFRA_OPT_GIT_AUTH_TOKEN=${CI_INFRA_OPT_GIT_AUTH_TOKEN:-your_CI_INFRA_OPT_GIT_AUTH_TOKEN}
    #- JENKINS_URL=http://jenkins.local:8080 <secret> <slave_name>
    #- JENKINS_URL=http://jenkins.local:8080/computer/<slave_name>/slave-agent.jnlp -jnlpCredentials <username>:<token>
    - JENKINS_URL=${JENKINS_URL}

networks:
  default:
    external: true
    name: oss-network

volumes:
  volume-jenkins-jnlp-slave: {}
