#!/bin/bash

update_ca() {
  echo "Updating CA certificates..."
  cp "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}"
  update-ca-certificates --fresh >/dev/null
}

if [ -f /var/run/docker.sock ]; then
    chown root:gitlab-runner /var/run/docker.sock
    chmod 660 /var/run/docker.sock
fi

if [ ! -d ~/.docker ]; then mkdir -p ~/.docker; chmod 775 ~/.docker; fi
if [ ! -d ~/.m2 ]; then mkdir -p ~/.m2; chmod 775 ~/.m2; fi
if [ ! -d ~/.ssh ]; then mkdir -p ~/.ssh; chmod 775 ~/.ssh; fi
if [ ! -d ~/.gnupg ]; then mkdir -p ~/.gnupg; chmod 775 ~/.gnupg; fi

if [ ! -f ~/.ssh/config ]; then
    touch ~/.ssh/config
    echo -e "Host *
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null" > ~/.ssh/config
fi
chmod 700 ~/.ssh
chmod 644 ~/.ssh/config

chown -R gitlab-runner:gitlab-runner ~

# gitlab-runner's config directory
CONFIG_DIR="/etc/gitlab-runner"
CONFIG_FILE=${CONFIG_FILE:-${CONFIG_DIR}/config.toml}

# custom certificate authority path
CA_CERTIFICATES_PATH=${CA_CERTIFICATES_PATH:-${CONFIG_DIR}/certs/ca.crt}
LOCAL_CA_PATH="/usr/local/share/ca-certificates/ca.crt"

if [ -f "${CA_CERTIFICATES_PATH}" ]; then
  # update the ca if the custom ca is different than the current
  cmp --silent "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}" || update_ca
fi

# launch gitlab-ci-multi-runner passing all arguments
exec sudo gitlab-ci-multi-runner "$@"
