apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: gitlab-runner
  labels:
    app: gitlab-runner
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab-runner
    spec:
      containers:
      - image: home1oss/gitlab-runner:9.1.1-xenial
        name: gitlab-runner
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
          requests:
            cpu: "1"
            memory: 1024Mi
        env:
          - name: INFRASTRUCTURE_CONF_GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: gitlab-runner-secret
                key: INFRASTRUCTURE_CONF_GIT_TOKEN
        volumeMounts:
          - name: var-run-docker-dot-sock
            mountPath: /var/run/docker.sock
# Download any file needed by CI, do not mount them
#          - name: home-gitlab-runner
#            mountPath: /home/gitlab-runner
#          - name: etc-gitlab-runner
#            mountPath: /etc/gitlab-runner
      volumes:
        - name: var-run-docker-dot-sock
          hostPath:
            path: /var/run/docker.sock
#        - name: home-gitlab-runner
#          hostPath:
#            path: /root/.oss/gitlab-runner.internal/home/gitlab-runner
#          nfs:
#            server: <host>
#            path: "/root/gitlab-runner"
#        - name: etc-gitlab-runner
#          hostPath:
#             path: /root/.oss/gitlab-runner.internal/etc/gitlab-runner
#          nfs:
#            server: <host>
#            path: "/root/gitlab-runner/etc"
