
version: '2.1'
services:
  git:
    build:
      context: .
      dockerfile: Dockerfile
    image: home1oss/gitlab:9.1.4-ce.0
    restart: always
    container_name: ${GIT_HOSTNAME:-gitlab.local}
    hostname: ${GIT_HOSTNAME:-gitlab.local}
    ports:
    - "20022:22"
    - "${GIT_EXTERNAL_PORT:-10080}:${GIT_PORT:-80}"
    volumes:
    # for script develop & debug
    #- ./docker/git_init.sh:/app/gitlab/git_init.sh
    #- ./docker/entrypoint.sh:/app/gitlab/entrypoint.sh
    #- ./docker/gitlab_utils.sh:/app/gitlab/gitlab_utils.sh
    # for auto repo init
    #- gitlab-volume:${GIT_VOLUME:-/app/gitlab/data}
    - ../../:${GIT_VOLUME:-/app/gitlab/data}/workspace
    # keep gitlab's data
    - gitlab-volume:/data
    - ${HOME}/.oss/${GIT_HOSTNAME:-gitlab.local}/etc/gitlab:/etc/gitlab
    - ${HOME}/.oss/${GIT_HOSTNAME:-gitlab.local}/var/opt/gitlab:/var/opt/gitlab
    - ${HOME}/.oss/${GIT_HOSTNAME:-gitlab.local}/var/log/gitlab:/var/log/gitlab
    environment:
    - CONFIGSERVER_WEBHOOK_ENDPOINT=${CONFIGSERVER_WEBHOOK_ENDPOINT:-http://configserver.local:8888/monitor}
    - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD:-user_pass}
    # 'admin' is preserved by gitlab
    - GIT_ADMIN_USERNAME=${GIT_ADMIN_USERNAME:-user}
    - GIT_DEPLOY_KEY=${GIT_DEPLOY_KEY:-/app/gitlab/data/default_deploy_key.pub}
    - GIT_HOSTNAME=${GIT_HOSTNAME:-gitlab.local}
    - GIT_HTTP_PORT=80
    - GIT_SSH_PORT=22
    - GIT_VOLUME=${GIT_VOLUME:-/app/gitlab/data}
    - GIT_WORKSPACE=${GIT_VOLUME:-/app/gitlab/data}/workspace
    - SKIP_AUTO_REPO_INIT=${SKIP_AUTO_REPO_INIT:-true}
    external_links:
    - configserver.local:configserver.local
volumes:
  gitlab-volume: {}

networks:
  default:
    external:
      name: oss-network
