
version: '3.6'
services:
  gitlab:
    build:
      context: .
      dockerfile: Dockerfile
    image: cirepo/gitlab:10.8.1-ce.0
    restart: always
    container_name: ${GIT_DOMAIN:-gitlab}.${INFRASTRUCTURE:-local}
    hostname: ${GIT_DOMAIN:-gitlab}.${INFRASTRUCTURE:-local}
    ports:
    - "${GITLAB_SHELL_SSH_PORT:-20022}:${GITLAB_SHELL_SSH_PORT:-20022}"
    - "${GIT_HTTP_PORT:-10080}:${GIT_HTTP_PORT:-10080}"
    volumes:
    # for auto repo init
    - volume-gitlab-git_volume:${GIT_VOLUME:-/app/gitlab/data}
    - ${WORKSPACE_ON_HOST:-../../}:${GIT_VOLUME:-/app/gitlab/data}/workspace
    # keep gitlab's data
    - volume-gitlab-etc_gitlab:/etc/gitlab
    - volume-gitlab-var_log_gitlab:/var/log/gitlab
    - volume-gitlab-var_opt_gitlab:/var/opt/gitlab
    #- ${HOME}/.ci-and-cd/${GIT_DOMAIN:-gitlab}.${INFRASTRUCTURE:-local}/etc/gitlab:/etc/gitlab
    #- ${HOME}/.ci-and-cd/${GIT_DOMAIN:-gitlab}.${INFRASTRUCTURE:-local}/var/log/gitlab:/var/log/gitlab
    #- ${HOME}/.ci-and-cd/${GIT_DOMAIN:-gitlab}.${INFRASTRUCTURE:-local}/var/opt/gitlab:/var/opt/gitlab
    environment:
    - CONFIGSERVER_WEBHOOK_ENDPOINT=${CONFIGSERVER_WEBHOOK_ENDPOINT:-http://oss-configserver.local:8888/monitor}
    - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD:-root_pass}
    - GITLAB_SHELL_SSH_PORT=${GITLAB_SHELL_SSH_PORT:-20022}
    - GIT_ADMIN_PASSWORD=${GIT_ADMIN_PASSWORD:-user_pass}
    # 'admin' is preserved by gitlab
    - GIT_ADMIN_USERNAME=${GIT_ADMIN_USERNAME:-user}
    - GIT_DEPLOY_KEY=${GIT_DEPLOY_KEY:-/app/gitlab/data/default_deploy_key.pub}
    - GIT_HOSTNAME=${GIT_DOMAIN:-gitlab}.${INFRASTRUCTURE:-local}
    - GIT_HTTP_PORT=${GIT_HTTP_PORT:-10080}
    - GIT_VOLUME=${GIT_VOLUME:-/app/gitlab/data}
    - GIT_WORKSPACE=${GIT_VOLUME:-/app/gitlab/data}/workspace
    - SKIP_AUTO_REPO_INIT=${SKIP_AUTO_REPO_INIT:-true}

# test:
#export GITLAB_ROOT_PASSWORD=root_pass
#export GITLAB_SHELL_SSH_PORT=20022
#export GIT_ADMIN_PASSWORD=user_pass
#export GIT_ADMIN_USERNAME=user
#export GIT_HTTP_PORT=10080
#export GIT_VOLUME=/tmp
#docker-compose up gitlab-test
#source ./docker/gitlab_utils.sh
#echo $(git_service_login root root_pass)
#curl --header "Authorization: Bearer $(git_service_login root root_pass)" http://gitlab.local:10080/api/v4/projects
#docker-compose down -v
#
#  gitlab-test:
#    image: gitlab/gitlab:10.7.3-ce.0
#    container_name: ${GIT_DOMAIN:-gitlab-test}.${INFRASTRUCTURE:-local}
#    hostname: ${GIT_DOMAIN:-gitlab-test}.${INFRASTRUCTURE:-local}
#    ports:
#    - "${GITLAB_SHELL_SSH_PORT:-20022}:22"
#    - "${GIT_HTTP_PORT:-10080}:80"
#    environment:
#    - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD:-root_pass}
#    #volumes:
#    # for script develop & debug
#    #- ./docker/git_init.sh:/app/gitlab/git_init.sh
#    #- ./docker/entrypoint.sh:/app/gitlab/entrypoint.sh
#    #- ./docker/gitlab_utils.sh:/app/gitlab/gitlab_utils.sh


networks:
  default:
    external: true
    name: oss-network

volumes:
  volume-gitlab-etc_gitlab: {}
  volume-gitlab-git_volume: {}
  volume-gitlab-var_log_gitlab: {}
  volume-gitlab-var_opt_gitlab: {}
