
version: '2.1'
services:
  gitlab-runner:
    image: home1oss/gitlab-runner:9.1.1-xenial
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: oss-gitlab-runner
    hostname: oss-gitlab-runner
    network_mode: host
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    # gitlab-runner user's home directory
    - ${HOME}/gitlab-runner/home:/home/gitlab-runner
    # gitlab-runner's config directory
    - ${HOME}/gitlab-runner/etc:/etc/gitlab-runner
    environment:
    - GIT_SERVICE_TOKEN=${GIT_SERVICE_TOKEN:-your_GIT_SERVICE_TOKEN}

networks:
  default:
    external:
      name: oss-network
