
version: '2.1'
services:
  base-gitlab-runner:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - CI_INFRA_OPT_GIT_AUTH_TOKEN=${CI_INFRA_OPT_GIT_AUTH_TOKEN:-your_CI_INFRA_OPT_GIT_AUTH_TOKEN}
    image: cirepo/gitlab-runner:10.5.0-bionic
    restart: always
