
version: '3.6'
services:
  gitlab-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${GITLAT_RUNNER_DOMAIN:-gitlab-runner}.${INFRASTRUCTURE:-local}
    environment:
    - INFRASTRUCTURE_CONF_GIT_TOKEN=${INFRASTRUCTURE_CONF_GIT_TOKEN:-your_INFRASTRUCTURE_CONF_GIT_TOKEN}
    #external_links:
    #- ${NEXUS3_PROXY_DOMAIN:-nexus3}.${INFRASTRUCTURE:-local}:${FILESERVER_DOMAIN:-fileserver.local}
    #- ${NEXUS3_PROXY_DOMAIN:-nexus3}.${INFRASTRUCTURE:-local}:${DOCKER_MIRROR_DOMAIN:-mirror.docker.local}
    #- ${NEXUS3_PROXY_DOMAIN:-nexus3}.${INFRASTRUCTURE:-local}:${DOCKER_REGISTRY_DOMAIN:-registry.docker.local}
    hostname: ${GITLAT_RUNNER_DOMAIN:-gitlab-runner}.${INFRASTRUCTURE:-local}
    image: home1oss/gitlab-runner:10.5.0-bionic
    # host type networking can't be used with links. This would result in undefined behavior
    #network_mode: host
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    # gitlab-runner user's home directory
    - volume-gitlab-runner-home_gitlab-runner:/home/gitlab-runner
    # gitlab-runner's config directory
    - volume-gitlab-runner-etc_gitlab-runner:/etc/gitlab-runner

networks:
  default:
    external: true
    name: oss-network

volumes:
  volume-gitlab-runner-home_gitlab-runner: {}
  volume-gitlab-runner-etc_gitlab-runner: {}
