
version: '3.6'
services:
  jenkins-swarm-slave:
    build:
      context: .
      dockerfile: Dockerfile
    image: cirepo/jenkins-swarm-slave:3.12-bionic
    restart: always
    command: ["-username", "slave", "-password", "slave_pass", "-executors", "5"]
    container_name: ${JENKINS_SLAVE_DOMAIN:-jenkins-swarm-slave}.${INFRASTRUCTURE:-local}
    hostname: ${JENKINS_SLAVE_DOMAIN:-jenkins-swarm-slave}.${INFRASTRUCTURE:-local}
    #external_links:
    #- jenkins.${INFRASTRUCTURE:-local}:jenkins.${INFRASTRUCTURE:-local}
    #- nexus.${INFRASTRUCTURE:-local}:nexus3.${INFRASTRUCTURE:-local}
    #- mvnsite.${INFRASTRUCTURE:-local}:mvnsite.${INFRASTRUCTURE:-local}
    volumes:
    - volume-jenkins-swarm-slave:/home/jenkins-slave
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - CI_INFRA_OPT_GIT_AUTH_TOKEN=${CI_INFRA_OPT_GIT_AUTH_TOKEN:-your_CI_INFRA_OPT_GIT_AUTH_TOKEN}
    - JENKINS_PORT_8080_TCP_ADDR=${JENKINS_PORT_8080_TCP_ADDR:-jenkins}.${INFRASTRUCTURE:-local}
    - JENKINS_PORT_8080_TCP_PORT=${JENKINS_PORT_8080_TCP_PORT:-8080}


networks:
  default:
    external: true
    name: oss-network

volumes:
  volume-jenkins-swarm-slave: {}
